### PR TITLE
Modernize dependencies and static analysis

### LINKED ISSUE #54: Support psr/http-message 2.0
The current requirement of only psr/http-message 1.0 prevents using this library with any project which depends on psr/http-message 2.0.

Can the dependency requirement be updated to support psr/http-message 2.0? I'm happy to open a merge request to do this.

### PR DESCRIPTION
**Pull request by theodorejb**
* Minimum PHP version is now 8.0
* Updated psr/http-message and teapot/status-code dependencies
* Added native type declarations
* Switched from PHP_CodeSniffer to PHP-CS-Fixer (using same configuration as [teapot-php/status-code](https://github.com/teapot-php/status-code))
* Enabled Psalm static analysis
* Migrated to GitHub Actions for CI instead of Travis

Resolves #54

### CODE REVIEW

**Comment by theodorejb** [comment]
@shrikeh Can you review this?

**Comment by localheinz** [comment]
@theodorejb 

I believe @shrikeh has moved most - if not all - of this code into the @teapot-php organization.

Can you take a look there?

**Comment by theodorejb** [comment]
@localheinz I did look in the @teapot-php org, but it doesn't seem to contain any of this code. The [teapot](https://github.com/teapot-php/teapot) repository there is empty.

**Comment by shrikeh** [comment]
I shall investigate tomorrow!

**Comment by shrikeh** [comment]
OK thoughts, as I finally have a little development time as we have a Bank Holiday here.

- Accept or improve any PRs here
- Migrate this entirely to the teapot org
- Keep this as a metapackage to the teapot/status-codes repo.
- Finally get around to the validator
- `teapot/teapot` will get both the validator and the status codes.

Thoughts?

**Comment by theodorejb** [comment]
One thing to consider is that there are currently [41 libraries in Packagist that depend on shrikeh/teapot](https://packagist.org/packages/shrikeh/teapot/dependents?order_by=downloads) (plus who knows how many additional private projects). So if you decide to migrate the project to the teapot org, I would still leave the name as **shrikeh/teapot** in Packagist so as to not disrupt the ecosystem.

**Comment by shrikeh** [comment]
Good point. OK, so to ensure we don't break downstream:

* `shrikeh/teapot` in the packagist sense will point to a `composer.json` at https://github.com/shrikeh/teapot
* The contents of that composer.json will list in the `require` section the `teapot/status-code` package. There will be no code left in https://github.com/shrikeh/teapot except some READMEs etc.
* `teapot/teapot` in packagist will include both the status code library and the validator.

@localheinz what do you reckon?

**Comment by theodorejb** [comment]
If you want the project to be [teapot-php/teapot](https://github.com/teapot-php/teapot) on GitHub, the current empty repository there should first be deleted and then this one transferred there. That way it won't lose stars, pull requests, and contributor history, and existing links to https://github.com/shrikeh/teapot will automatically redirect to the new location.

This doesn't require changing the name in Packagist, but simply editing the package URL there (see https://github.com/composer/packagist/issues/47). I'm not sure if it's a good idea to try to support two different names for the Packagist library, as an extra repository would have to be set up for this, and the new package name would not keep the download stats (currently over 1.7 million downloads), dependents, and suggesters that [shrikeh/teapot](https://packagist.org/packages/shrikeh/teapot) has.

**Comment by shrikeh** [comment]
Good point. OK, I think I see what you're saying

**Pull request merged**
