### PR TITLE
Fix: Remove leading slash when importing, remove unused imports

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] removes the leading slash when importing namespaces
* [x] removes unused imports

### CODE REVIEW

**Comment by shrikeh** [comment]
Quick q: I always put the leading slash to aid in making sure my paths are all good. Are you recommending they drop as they are overkill?

**Comment by localheinz** [comment]
@shrikeh 

I wouldn't say that it is overkill, but it is not needed. See http://stackoverflow.com/questions/4849279/importing-classes-and-namespaces-in-php-what-difference-does-a-leading-backslas.

**Comment by shrikeh** [comment]
Sold!

**Comment by localheinz** [comment]
@shrikeh 

:+1:

**Pull request merged**
